"""
TrustLens AI – Interactive CLI Setup Wizard

Run before starting the backend to configure your LLM provider.
Handles:
  1. Grok (xAI) – enter API key
  2. Gemini (Google) – enter API key
  3. Anthropic (Claude) – enter API key
  4. OpenAI (GPT) – enter API key
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

# ── ANSI Colours ──────────────────────────────────────────────────────

BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"
GREEN = "\033[92m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
RED = "\033[91m"
MAGENTA = "\033[95m"
BLUE = "\033[94m"
WHITE = "\033[97m"

# ── Paths ─────────────────────────────────────────────────────────────

ENV_FILE = Path(__file__).resolve().parent / ".env"

# Keys that the wizard writes (cleared on exit)
WIZARD_KEYS = [
    "TRUSTLENS_AI_PROVIDER",
    "TRUSTLENS_OPENAI_API_KEY",
    "TRUSTLENS_OPENAI_MODEL",
    "TRUSTLENS_ANTHROPIC_API_KEY",
    "TRUSTLENS_ANTHROPIC_MODEL",
    "TRUSTLENS_GROK_API_KEY",
    "TRUSTLENS_GROK_MODEL",
    "TRUSTLENS_GEMINI_API_KEY",
    "TRUSTLENS_GEMINI_MODEL",
]

# ── Provider Definitions ─────────────────────────────────────────────

PROVIDERS = [
    {
        "num": "1",
        "name": "Grok (xAI)",
        "key": "grok",
        "color": BLUE,
        "icon": "🤖",
    },
    {
        "num": "2",
        "name": "Gemini (Google)",
        "key": "gemini",
        "color": CYAN,
        "icon": "💎",
    },
    {
        "num": "3",
        "name": "Anthropic (Claude)",
        "key": "anthropic",
        "color": MAGENTA,
        "icon": "🧠",
    },
    {
        "num": "4",
        "name": "OpenAI (GPT)",
        "key": "openai",
        "color": YELLOW,
        "icon": "⚡",
    },
]

DEFAULT_MODELS = {
    "grok": "grok-3",
    "gemini": "gemini-2.5-flash",
    "anthropic": "claude-sonnet-4-20250514",
    "openai": "gpt-4o",
}


# ── .env helpers ──────────────────────────────────────────────────────


def _read_env() -> dict[str, str]:
    """Read .env into an ordered dict (preserves comments as keys)."""
    data: dict[str, str] = {}
    if not ENV_FILE.exists():
        return data
    for line in ENV_FILE.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" in stripped:
            k, v = stripped.split("=", 1)
            data[k.strip()] = v.strip()
    return data


def _write_env(data: dict[str, str]) -> None:
    """Write key=value pairs to .env, preserving any existing non-wizard keys."""
    existing: dict[str, str] = {}
    comments: list[str] = []

    # Read existing file to preserve non-wizard config and comments
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                comments.append(line)
                continue
            if "=" in stripped:
                k, v = stripped.split("=", 1)
                existing[k.strip()] = v.strip()

    # Merge: wizard data overrides, rest preserved
    existing.update(data)

    lines: list[str] = []
    # Write header
    lines.append("# TrustLens AI Configuration")
    lines.append("# Auto-generated by setup wizard — cleared on exit")
    lines.append("")

    for k, v in existing.items():
        lines.append(f"{k}={v}")

    lines.append("")
    ENV_FILE.write_text("\n".join(lines) + "\n")


def _get_saved_config() -> dict[str, str] | None:
    """Check if there's a saved LLM config in .env. Returns provider info or None."""
    env = _read_env()
    provider = env.get("TRUSTLENS_AI_PROVIDER", "").strip()
    if not provider:
        return None

    # Build a summary of what's saved
    info: dict[str, str] = {"provider": provider}
    key_map = {
        "openai": ("TRUSTLENS_OPENAI_MODEL", "TRUSTLENS_OPENAI_API_KEY"),
        "anthropic": ("TRUSTLENS_ANTHROPIC_MODEL", "TRUSTLENS_ANTHROPIC_API_KEY"),
        "grok": ("TRUSTLENS_GROK_MODEL", "TRUSTLENS_GROK_API_KEY"),
        "gemini": ("TRUSTLENS_GEMINI_MODEL", "TRUSTLENS_GEMINI_API_KEY"),
    }
    model_key, api_key = key_map.get(provider, ("", ""))
    if model_key:
        info["model"] = env.get(model_key, "default")
    if api_key:
        raw = env.get(api_key, "")
        info["has_key"] = "yes" if raw else "no"
    return info


def _clear_wizard_config() -> None:
    """Remove wizard-managed keys from .env."""
    if not ENV_FILE.exists():
        return

    existing = _read_env()
    cleaned = {k: v for k, v in existing.items() if k not in WIZARD_KEYS}

    if not cleaned:
        ENV_FILE.unlink(missing_ok=True)
        print(f"\n{YELLOW}🧹 Cleared LLM config — fresh selection next time.{RESET}")
        return

    lines = ["# TrustLens AI Configuration", ""]
    for k, v in cleaned.items():
        lines.append(f"{k}={v}")
    lines.append("")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\n{YELLOW}🧹 Cleared LLM config — fresh selection next time.{RESET}")


# ── Banner ────────────────────────────────────────────────────────────


def _print_banner() -> None:
    banner = f"""
{CYAN}{BOLD}╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║   ████████╗██████╗ ██╗   ██╗███████╗████████╗                ║
║   ╚══██╔══╝██╔══██╗██║   ██║██╔════╝╚══██╔══╝                ║
║      ██║   ██████╔╝██║   ██║███████╗   ██║                   ║
║      ██║   ██╔══██╗██║   ██║╚════██║   ██║                   ║
║      ██║   ██║  ██║╚██████╔╝███████║   ██║                   ║
║      ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝                   ║
║                                                              ║
║          {WHITE}L E N S   A I{CYAN}   Setup Wizard                      ║
║          {DIM}Explainable URL Trust Intelligence{RESET}{CYAN}{BOLD}                ║
║                                                              ║
║          {DIM}by Abhishek Verma @abhishekayu{RESET}{CYAN}{BOLD}                    ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝{RESET}
"""
    print(banner)


def _setup_cloud_provider(provider_key: str, provider_name: str, color: str) -> dict[str, str] | None:
    """Interactive cloud provider setup: get API key, optional model override."""
    default_model = DEFAULT_MODELS[provider_key]

    print(f"\n{color}{BOLD}{provider_name} Setup{RESET}")
    print(f"{DIM}{'─' * 50}{RESET}")

    # API Key URLs
    urls = {
        "grok": "https://console.x.ai",
        "gemini": "https://aistudio.google.com/apikey",
        "anthropic": "https://console.anthropic.com/settings/keys",
        "openai": "https://platform.openai.com/api-keys",
    }

    url = urls.get(provider_key, "")
    if url:
        print(f"\n   {DIM}Get your API key at: {CYAN}{url}{RESET}")

    while True:
        try:
            api_key = input(f"\n{BOLD}➤ Paste your API key: {RESET}").strip()
        except (EOFError, KeyboardInterrupt):
            return None

        if not api_key:
            print(f"{RED}   API key cannot be empty.{RESET}")
            continue

        if len(api_key) < 10:
            print(f"{RED}   That doesn't look like a valid API key. Try again.{RESET}")
            continue

        break

    # Model selection
    print(f"\n   {DIM}Default model: {WHITE}{BOLD}{default_model}{RESET}")
    try:
        custom = input(f"{BOLD}➤ Model name (Enter for default): {RESET}").strip()
    except (EOFError, KeyboardInterrupt):
        custom = ""

    model = custom if custom else default_model

    key_prefix = provider_key.upper()
    result = {
        "TRUSTLENS_AI_PROVIDER": provider_key,
        f"TRUSTLENS_{key_prefix}_API_KEY": api_key,
        f"TRUSTLENS_{key_prefix}_MODEL": model,
    }

    print(f"\n{GREEN}✅ {provider_name} configured!{RESET}")
    print(f"   {DIM}Provider: {provider_key} | Model: {model}{RESET}")

    return result


# ── Main Wizard ───────────────────────────────────────────────────────


def run_wizard() -> dict[str, str] | None:
    """
    Run the interactive LLM setup wizard.

    Returns the env config dict on success, None on cancel.
    Returns "continue" string if user wants to keep saved config.
    """
    _print_banner()

    # ── Check for saved config ────────────────────────────────────────
    saved = _get_saved_config()

    if saved:
        provider_name = saved["provider"].upper()
        model = saved.get("model", "default")
        has_key = saved.get("has_key", "")

        print(f"{GREEN}{BOLD}  ✅ Saved configuration found:{RESET}")
        print(f"     Provider: {CYAN}{BOLD}{provider_name}{RESET}")
        print(f"     Model:    {WHITE}{BOLD}{model}{RESET}")
        if has_key:
            key_status = f"{GREEN}set{RESET}" if has_key == "yes" else f"{RED}not set{RESET}"
            print(f"     API Key:  {key_status}")

        print(f"\n   {GREEN}{BOLD}C.{RESET} ▶  Continue with saved config")
        print(f"   {YELLOW}{BOLD}N.{RESET} 🔄 Pick a new LLM provider")
        print(f"   {RED}{BOLD}Q.{RESET} ✖  Quit\n")

        while True:
            try:
                choice = input(f"{BOLD}➤ Choice (C/N/Q): {RESET}").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print(f"\n{YELLOW}👋 Exiting.{RESET}")
                return None

            if choice in ("c", "continue", ""):
                print(f"\n{GREEN}▶  Continuing with {CYAN}{BOLD}{provider_name}{RESET}{GREEN} ({model}){RESET}")
                return "continue"  # type: ignore[return-value]
            elif choice in ("n", "new"):
                break  # Fall through to provider selection
            elif choice in ("q", "quit"):
                return None
            else:
                print(f"{RED}   Enter C, N, or Q.{RESET}")

        print()  # blank line before provider list

    # ── Provider selection ────────────────────────────────────────────
    print(f"{WHITE}{BOLD}  Choose your LLM provider:{RESET}\n")

    for p in PROVIDERS:
        print(f"   {p['color']}{BOLD}{p['num']}.{RESET} {p['icon']}  {p['name']}")

    print(f"\n   {DIM}Press Ctrl+C to exit{RESET}")

    while True:
        try:
            choice = input(f"\n{BOLD}➤ Select provider (1-4): {RESET}").strip()
        except (EOFError, KeyboardInterrupt):
            print(f"\n{YELLOW}👋 Setup cancelled.{RESET}")
            return None

        provider = next((p for p in PROVIDERS if p["num"] == choice), None)
        if not provider:
            print(f"{RED}   Invalid choice. Enter 1-4.{RESET}")
            continue

        return _setup_cloud_provider(
            provider["key"], provider["name"], provider["color"]
        )


# ── Entry point ───────────────────────────────────────────────────────


def main() -> None:
    """
    Entry point: run wizard → save config → start uvicorn.
    Config is saved persistently. Use 'N' at next startup to pick a new provider.
    """
    # Run the wizard
    config = run_wizard()
    if config is None:
        print(f"\n{RED}Setup cancelled. Exiting.{RESET}")
        sys.exit(1)

    # If user chose "Continue", config is already in .env — just start
    if config == "continue":
        provider = _read_env().get("TRUSTLENS_AI_PROVIDER", "unknown")
    else:
        # Write new config to .env
        _write_env(config)
        provider = config.get("TRUSTLENS_AI_PROVIDER", "unknown")

    print(f"\n{GREEN}{BOLD}{'═' * 50}{RESET}")
    print(f"{GREEN}{BOLD}  🚀 Starting TrustLens AI with {provider.upper()}{RESET}")
    print(f"{GREEN}{BOLD}{'═' * 50}{RESET}\n")

    # Start uvicorn
    try:
        os.chdir(ENV_FILE.parent)

        subprocess.run(
            [
                sys.executable,
                "-m",
                "uvicorn",
                "trustlens.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "--reload",
            ],
            env={**os.environ, "TRUSTLENS_WIZARD_DONE": "1"},
            check=True,
        )
    except subprocess.CalledProcessError:
        print(f"\n{RED}Server exited with error.{RESET}")
    except KeyboardInterrupt:
        print(f"\n{YELLOW}👋 Server stopped.{RESET}")


if __name__ == "__main__":
    main()
